[pytest]
# Configuración de pytest
markers =
    suma: Pruebas relacionadas con la función de suma
    resta: Pruebas relacionadas con la función de resta
    multiplicacion: Pruebas relacionadas con la función de multiplicación
    division: Pruebas relacionadas con la función de división